class SCCASPartAgeGenderIdentifiers:
    """Identifiers for age and gender."""
    TODDLER_HUMAN_MALE = 'pm'
    TODDLER_HUMAN_FEMALE = 'pf'
    TODDLER_HUMAN_UNISEX = 'pu'
    CHILD_HUMAN_MALE = 'cm'
    CHILD_HUMAN_FEMALE = 'cf'
    CHILD_HUMAN_UNISEX = 'cu'
    TEEN_HUMAN_MALE = 'tm'
    TEEN_HUMAN_FEMALE = 'tf'
    TEEN_HUMAN_UNISEX = 'tu'
    YOUNG_ADULT_HUMAN_MALE = 'ym'
    YOUNG_ADULT_HUMAN_FEMALE = 'yf'
    YOUNG_ADULT_HUMAN_UNISEX = 'yu'
    ADULT_HUMAN_MALE = 'am'
    ADULT_HUMAN_FEMALE = 'af'
    ADULT_HUMAN_UNISEX = 'au'
    ELDER_HUMAN_MALE = 'em'
    ELDER_HUMAN_FEMALE = 'ef'
    ELDER_HUMAN_UNISEX = 'eu'
    CHILD_DOG = 'cd'
    ADULT_LARGE_DOG = 'ad'
    ADULT_SMALL_DOG = 'al'
    CHILD_CAT = 'cc'
    ADULT_CAT = 'ac'
